--- #YAML:1.0
name:                Email-MessageID
version:             1.351
abstract:            Generate world unique message-ids
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::Address:                1.80
    Sys::Hostname:                 1.1
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
