# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MessageID
version:      1.2
version_from: lib/Email/MessageID.pm
installdirs:  site
requires:
    Email::Address:                1.3
    Sys::Hostname:                 1.11
    Test::More:                    0.47
    Time::HiRes:                   1.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
