# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MessageID
version:      1.1
version_from: lib/Email/MessageID.pm
installdirs:  site
requires:
    Class::Trigger:                
    Email::Address:                
    Sys::Hostname:                 
    Test::More:                    
    Time::HiRes:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
